spring.application.name=Corporate-Travel
server.port=8080


#db configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Corporate_Travel
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


#logging file
logging.file.name=logs/application.log

logging.level.Booking.GDS.service=DEBUG

