CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    department_id BIGINT,
    designation VARCHAR(255),
    grade VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE travel_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(1000),
    policy_type VARCHAR(100),
    version INTEGER,
    effective_from DATE,
    effective_to DATE,
    grade VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE travel_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    purpose VARCHAR(255) NOT NULL,
    source_city VARCHAR(255) NOT NULL,
    destination_city VARCHAR(255) NOT NULL,
    departure_date DATE NOT NULL,
    return_date DATE NOT NULL,
    travel_class VARCHAR(50) NOT NULL,
    estimated_cost NUMERIC(12, 2),
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE policy_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id BIGINT NOT NULL REFERENCES travel_policy(id),
    rule_code VARCHAR(100),
    rule_type VARCHAR(100),
    rule_value VARCHAR(255),
    severity VARCHAR(50),
    description VARCHAR(1000),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE policy_validation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_request_id BIGINT NOT NULL REFERENCES travel_request(id),
    policy_id BIGINT NOT NULL REFERENCES travel_policy(id),
    validated_at TIMESTAMP,
    overall_status VARCHAR(50)
);

CREATE TABLE policy_violation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    validation_id BIGINT NOT NULL REFERENCES policy_validation(id),
    policy_rule_id BIGINT NOT NULL REFERENCES policy_rule(id),
    violation_type VARCHAR(100),
    message VARCHAR(1000),
    actual_value VARCHAR(255),
    allowed_value VARCHAR(255),
    severity VARCHAR(50),
    resolved BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_travel_request_employee_id ON travel_request(employee_id);
CREATE INDEX idx_travel_request_status ON travel_request(status);
CREATE INDEX idx_policy_rule_policy_id ON policy_rule(policy_id);
CREATE INDEX idx_policy_validation_travel_request_id ON policy_validation(travel_request_id);
CREATE INDEX idx_policy_validation_policy_id ON policy_validation(policy_id);
CREATE INDEX idx_policy_violation_validation_id ON policy_violation(validation_id);
CREATE INDEX idx_policy_violation_policy_rule_id ON policy_violation(policy_rule_id);
CREATE INDEX idx_travel_policy_grade_active ON travel_policy(grade, active);