ALTER TABLE travel_request ALTER COLUMN travel_class DROP NOT NULL;
ALTER TABLE travel_request ALTER COLUMN purpose DROP NOT NULL;
ALTER TABLE travel_request ALTER COLUMN departure_date DROP NOT NULL;
ALTER TABLE travel_request ALTER COLUMN return_date DROP NOT NULL;
ALTER TABLE travel_request ADD COLUMN IF NOT EXISTS distance NUMERIC(12, 2);
ALTER TABLE travel_request ADD COLUMN IF NOT EXISTS expense NUMERIC(12, 2);
UPDATE travel_request SET distance = 0 WHERE distance IS NULL;
UPDATE travel_request SET expense = COALESCE(estimated_cost, 0) WHERE expense IS NULL;
ALTER TABLE travel_request ALTER COLUMN distance SET NOT NULL;
ALTER TABLE travel_request ALTER COLUMN expense SET NOT NULL;

CREATE TABLE IF NOT EXISTS booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_request_id BIGINT NOT NULL UNIQUE REFERENCES travel_request(id),
    valid BOOLEAN NOT NULL,
    expected_cost NUMERIC(12, 2),
    expense NUMERIC(12, 2) NOT NULL,
    flag VARCHAR(1) NOT NULL,
    booked_at TIMESTAMP NOT NULL
);